### PR TITLE
feat: add Home Assistant MQTT auto-discovery + Docker support

### PR DESCRIPTION
**Pull request by ahochsteger**
@joscha82 this PR adds full support for Home Assistant using MQTT auto-discovery as well as many other improvements.

**Feature summary:**

* **MQTT auto-discovery** for **Home Assistant** (including availability status)
* **Docker Image** to easily run the MQTT bridge with HA support (e.g. on a Raspberry Pi)
* Many **environment variables** to fine-tune the behavior of MQTT and Home Assistant support
* Much improved **MQTT bridge** with **property-splitting** for array/object properties 
* Much improved **Wattpilot Shell** with many commands to interactively control, explore and diagnose Wattpilot with MQTT and Home Assistant
* Much enhanced and updated **API metada ([wattpilot.yaml](https://github.com/joscha82/wattpilot/blob/1317b44c3e57ea70320b695d1c166271cf33b38f/src/wattpilot/ressources/wattpilot.yaml) and generated [API.md](https://github.com/joscha82/wattpilot/blob/1317b44c3e57ea70320b695d1c166271cf33b38f/API.md))** to generically expose up to over 300 properties to MQTT and Home Assistant

The updated README.md contains information about how it can be used, configured and tested.

*Here are some screenshots:*
Screenshot_20220421_234051
Screenshot_20220421_234125

### CODE REVIEW

**Comment by thecem** [comment]
Thank you @ahochsteger ! 

Since I read yesterday that there is a lot of work done even on the developer site of go-e https://github.com/goecharger/go-eCharger-API-v2/issues/67#issuecomment-1078916808 (@ahochsteger there is something with mqtt bevor, did you use this?) and the codebase beside the WS is the in the same direction to have wattpilot and GO-E API in HA. Would this be an idea to integrate wattpilot support into the already existing custom_integration https://github.com/cathiele/homeassistant-goecharger ?
So there is only one integration to have the (mostly) same API of two (mostly) same HW in one integration.
If we could achieve to get the WebSicket working in @cathiele integration, this would be a benefit for all. And we have one mature integration and less work for everyone.

What do you thinking about this approach? @ahochsteger @joscha82 @mk-maddin @cathile

Thank you!

**Comment by mk-maddin** [comment]
@ahochsteger:
Looks really cool :)
How did you solve the attribute information of "namespace" values like e.g. WiFi Connection Information (property ccw) ?

**Comment by mk-maddin** [comment]
**Some Off Topic** - but I think we have a lot of knowledge here together ;)
Is on all your wattpilot devices the default Hotspot (SSID: Wattpilot_<serial> ) active all the time, too?
Did someone find a way (api / app / anything else) to disable the default hotspot/access poin?

**Comment by thecem** [comment]
Yes, always on! May https://github.com/peterpoetzi has an answer to this? @peterpoetzi ?

**Comment by joscha82** [comment]
> **Some Off Topic** - but I think we have a lot of knowledge here together ;) Is on all your wattpilot devices the default Hotspot (SSID: Wattpilot_ ) active all the time, too? Did someone find a way (api / app / anything else) to disable the default hotspot/access poin?

As far as i know thats not possibe, also i did  not see any property into that direction. 
There is an open issue/feature request also on go-e APIv2 Repo here: https://github.com/goecharger/go-eCharger-API-v2/issues/35

**Comment by ahochsteger** [comment]
> Looks really cool :)
Thanks :)

> How did you solve the attribute information of "namespace" values like e.g. WiFi Connection Information (property ccw) ?

This did the trick:
```python
class JSONNamespaceEncoder(json.JSONEncoder):
    # See https://gist.github.com/jdthorpe/313cafc6bdaedfbc7d8c32fcef799fbf
    def default(self, obj):
        if isinstance(obj, SimpleNamespace):
            return obj.__dict__
        return super(JSONNamespaceEncoder, self).default(obj)

def utils_value2json(value):
    return json.dumps(value, cls=JSONNamespaceEncoder)
```

**Comment by ahochsteger** [comment]
@thecem 
> Since I read yesterday that there is a lot of work done even on the developer site of go-e [goecharger/go-eCharger-API-v2#67 (comment)](https://github.com/goecharger/go-eCharger-API-v2/issues/67#issuecomment-1078916808) (@ahochsteger there is something with mqtt bevor, did you use this?)

No I've created a WebSocket-to-MQTT bridge and used that to provide Home Assistant Discovery Configuration via MQTT.

> and the codebase beside the WS is the in the same direction to have wattpilot and GO-E API in HA. Would this be an idea to integrate wattpilot support into the already existing custom_integration https://github.com/cathiele/homeassistant-goecharger ? So there is only one integration to have the (mostly) same API of two (mostly) same HW in one integration. If we could achieve to get the WebSicket working in @cathiele integration, this would be a benefit for all. And we have one mature integration and less work for everyone.
> 
> What do you thinking about this approach?

Yes, I agree that it would be good to join forces and avoid duplicate work.

I see **different approaches** here:
1. Enable direct **WebSocket support** in [homeassistant-goecharger](https://github.com/cathiele/homeassistant-goecharger) (as you suggested)
2. **Adjust the Websocket-to-MQTT bridge** to provide an (almost) go-eCharger compatible MQTT API so [homeassistant-goecharger](https://github.com/cathiele/homeassistant-goecharger) could be easily adopted
3. **Use the MQTT bridge** provided by this PR that also provides additional features in a generic way (e.g. translates integer enums to human-readable names and decompose array/object properties into their own properties (e.g. the total power entry of the `nrg` array is exposed as a separate property `nrg_ptotal`)
4. **Add Wattpilot support** to the fronius integration (either the [official Fronius integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/fronius) or [safepay.fronius](https://github.com/safepay/sensor.fronius) using HACS)
5. **Use [https://github.com/mk-maddin/wattpilot-HA](wattpilot-HA)** as the native Wattpilot integration for Home Assistant

They all have their pros and cons and may be better for different use cases, e.g.:
1. The 1st approach targets **Home Assistant users** and provides an easy way to integrate without the need of extra components (e.g. MQTT server, websocket-to-mqtt bridge).
2. The 2nd approach may reduce implementation effort, but at the cost of complexity on the user side (requires two additional components: MQTT server + MQTT bridge).
3. The 3rd approach targets **users of different smart home solutions** which all are able to integrate MQTT. Translating the values and splitting up complex properties makes it ease to integrate.
4. The 4th approach makes it easier for users of the fronius ecosystem to get a better out-of-the-box experience.
5. The 5th approach allows focussed and fast development of a Wattpilot integration for HA without having to take care of other implementations (e.g. go-eCharger or Fronius) at the cost of possible duplicate effort.

I think a good start would be to **put the API metadata into the core**of the Wattpilot library (see [wattpilot.yaml](https://github.com/joscha82/wattpilot/blob/443190b2426e4c7bc37a882f76779c125f723e2b/src/wattpilot/ressources/wattpilot.yaml) or [API.md](https://github.com/joscha82/wattpilot/blob/443190b2426e4c7bc37a882f76779c125f723e2b/API.md) - both part of this PR). This would allow to replace the hard-coded parsing of properties with the generic, metadata-driven approach. We can enrich the metadata with additional information and use that to drive all relevant approaches in a generic way (as the MQTT bridge already does).
This way both Wattpilot as well as GO eCharger would be easier to maintain in the future - esp. if firmware updates may introduce new properties.
@joscha82, @thecem, @mk-maddin, @cathiele what do you think?

**Comment by thecem** [comment]
Absolutely right, I think the most unique and best adoption ist the approach with Wattpilot.yaml and API.md. In may there will be new features for Wattpilot, so we are able to adopt all changes with ease.

**Comment by ahochsteger** [comment]
@joscha82 it would be great if you could merge this PR since it already contains so much working stuff so others could benefit from it as well :-).

Maybe we can talk about possible future refactorings to bring some functionality I've implemented for the shell and move it to the core library. Esp. the API metadata stuff (using wattpilot.yaml) would be good to have there and I see some ways to greatly simplify the code if it is based on the API metadata instead of hard-coded parsing of properties.

**Comment by joscha82** [comment]
> I see **different approaches** here:
> 
> 1. Enable direct **WebSocket support** in [homeassistant-goecharger](https://github.com/cathiele/homeassistant-goecharger) (as you suggested)
> 2. **Adjust the Websocket-to-MQTT bridge** to provide an (almost) go-eCharger compatible MQTT API so [homeassistant-goecharger](https://github.com/cathiele/homeassistant-goecharger) could be easily adopted
> 3. **Use the MQTT bridge** provided by this PR that also provides additional features in a generic way (e.g. translates integer enums to human-readable names and decompose array/object properties into their own properties (e.g. the total power entry of the `nrg` array is exposed as a separate property `nrg_ptotal`)
> 4. **Add Wattpilot support** to the fronius integration (either the [official Fronius integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/fronius) or [safepay.fronius](https://github.com/safepay/sensor.fronius) using HACS)
> 5. **Use [https://github.com/mk-maddin/wattpilot-HA](wattpilot-HA)** as the native Wattpilot integration for Home Assistant
> 
> They all have their pros and cons and may be better for different use cases, e.g.:
> 
> 1. The 1st approach targets **Home Assistant users** and provides an easy way to integrate without the need of extra components (e.g. MQTT server, websocket-to-mqtt bridge).
> 2. The 2nd approach may reduce implementation effort, but at the cost of complexity on the user side (requires two additional components: MQTT server + MQTT bridge).
> 3. The 3rd approach targets **users of different smart home solutions** which all are able to integrate MQTT. Translating the values and splitting up complex properties makes it ease to integrate.
> 4. The 4th approach makes it easier for **users of the fronius ecosystem** to get a better out-of-the-box experience.
> 5. The 5th approach allows focussed and **independent development of a Wattpilot integration for HA** without having to take care of other implementations (e.g. go-eCharger or Fronius) at the cost of possible duplicate effort.
> 
> I think a good start would be to **put the API metadata into the core** of the Wattpilot library (see [wattpilot.yaml](https://github.com/joscha82/wattpilot/blob/443190b2426e4c7bc37a882f76779c125f723e2b/src/wattpilot/ressources/wattpilot.yaml) or [API.md](https://github.com/joscha82/wattpilot/blob/443190b2426e4c7bc37a882f76779c125f723e2b/API.md) - both part of this PR). This would allow to replace the hard-coded parsing of properties with the generic, metadata-driven approach. We can enrich the metadata with additional information and use that to drive all relevant approaches in a generic way (as the MQTT bridge already does). This way both Wattpilot as well as GO eCharger would be easier to maintain in the future - esp. if firmware updates may introduce new properties. @joscha82, @thecem, @mk-maddin, @cathiele, @safepay, what do you think?

I would prefer your mqtt bridge instead  of building a API-compatible eGo Bridge, as your bridge is better suited for most Home Automation Systems (which i assume is the main use-case). 
Integration in the existing Fronius Inverter Integration is the wrong direction in my opinion. It is the fronius ecosystem and if Fronius wants to have the wallbox highly integrated, its on their end to adopt/implement their solar API on the wallbox itself. At the current stage the wattpilot feels more like a eGo Wallbox with a small  fronius Inverter Integration and stripped down API and not like a Fronius Wallbox. 
I also like the native HA Integration but given that mqtt is independent and a good choice for other home automation integrations i  would prefer that direction (also given that HA has nice mqtt autodiscovery-features). But both solutions can live nicely side by side and @mk-maddin integration is a good solution for HA Users who integrate natively without additional (external) dependencies.

**Comment by joscha82** [comment]
> @joscha82 it would be great if you could merge this PR since it already contains so much working stuff so others could benefit from it as well :-).
> 
> Maybe we can talk about possible future refactorings to bring some functionality I've implemented for the shell and move it to the core library. Esp. the API metadata stuff (using wattpilot.yaml) would be good to have there and I see some ways to greatly simplify the code if it is based on the API metadata instead of hard-coded parsing of properties.

I believe your idea to integrate API Metadata into the core library makes absolutely sense, and makes the included information usable by all consumers of the libary and not only for wattpilotshell.
Also I think it makes sense to divide wattpilotshell into two components: a) the shell (interactive and cmdline) and b) wattpilot2mqtt bridge.

I just found the time to test your pull request and will merge it now. I will also remove the now obsolete dependency on pyreadline and bump version requirement to python >3.10.

**Comment by ahochsteger** [comment]
> Also I think it makes sense to divide wattpilotshell into two components: a) the shell (interactive and cmdline) and b) wattpilot2mqtt bridge.

@joscha82 yes I agree - this makes absolutely sense.

**Pull request merged**
